name: Tackle commons-rest CI PR

on:
  pull_request:
    branches: [ main ]

jobs:
  unit-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.2.0
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        java-package: jdk
    - name: Cache Maven packages
      uses: actions/cache@v3.2.0
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2  
    - name: Build with Maven
      run: mvn -B test --file pom.xml

  integration-native-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.2.0
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        java-package: jdk
    - name: Cache Maven packages
      uses: actions/cache@v3.2.0
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2  
    - name: Build with Maven
      run: mvn -B verify -Pnative -Dquarkus-profile=test --file pom.xml

  code-coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.2.0
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        java-package: jdk
    - name: Cache Maven packages
      uses: actions/cache@v3.2.0
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Generate jacoco report
      run: mvn clean test -Pjacoco --file pom.xml && mvn jacoco:restore-instrumented-classes@default-restore-instrumented-classes jacoco:report-aggregate@report-aggregate -Pjacoco --file pom.xml
    - uses: codecov/codecov-action@v2.0.3
      with:
        file: ./commons-rest-sample/target/site/jacoco-aggregate/jacoco.xml
        name: codecov
